"""empty message

Revision ID: 2e8114855bc5
Revises: 
Create Date: 2020-10-21 14:49:51.992248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8114855bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('dpi', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('heart_rate', sa.Numeric(), nullable=True),
    sa.Column('has_mask', sa.Boolean(), nullable=True),
    sa.Column('has_face_shield', sa.Boolean(), nullable=True),
    sa.Column('has_rules', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('dpi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
