"""empty message

Revision ID: 60567d7de3f0
Revises: 2e8114855bc5
Create Date: 2020-10-21 15:54:05.857281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60567d7de3f0'
down_revision = '2e8114855bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('heart_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dpi'], ['user.dpi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_symptoms')
    # ### end Alembic commands ###
