"""empty message

Revision ID: f54582a4b18e
Revises: 
Create Date: 2020-10-21 16:40:04.322123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54582a4b18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('dpi', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('heart_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('has_mask', sa.Boolean(), nullable=True),
    sa.Column('has_face_shield', sa.Boolean(), nullable=True),
    sa.Column('has_rules', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('dpi')
    )
    op.create_table('user_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('heart_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dpi'], ['user.dpi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_symptoms')
    op.drop_table('user')
    # ### end Alembic commands ###
